# Generated by Django 6.0.6 on 2026-07-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='number_of_views',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
