# Generated by Django 6.0.6 on 2026-07-18 00:11
# Customized to safely preserve data: rename isPublished -> is_published and
# backfill unique slugs for existing rows.

from django.db import migrations, models
from django.utils.text import slugify


def backfill_slugs(apps, schema_editor):
    """Populate a unique slug for every existing Blog row."""
    Blog = apps.get_model("blog", "Blog")
    used = set()
    for blog in Blog.objects.order_by("id"):
        base = slugify(blog.title) or f"post-{blog.id}"
        slug = base
        counter = 1
        while slug in used:
            counter += 1
            slug = f"{base}-{counter}"
        used.add(slug)
        blog.slug = slug
        blog.save(update_fields=["slug"])


def revert_slugs(apps, schema_editor):
    Blog = apps.get_model("blog", "Blog")
    Blog.objects.update(slug="")


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_number_of_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_at'], 'verbose_name': 'blog post', 'verbose_name_plural': 'blog posts'},
        ),
        # Rename (not drop+add) so existing isPublished values are preserved.
        migrations.RenameField(
            model_name='blog',
            old_name='isPublished',
            new_name='is_published',
        ),
        migrations.AlterField(
            model_name='blog',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Only published posts are visible to site visitors.', verbose_name='published'),
        ),
        # Add slug WITHOUT the unique constraint first so existing rows can be
        # backfilled safely (otherwise the table remake would violate UNIQUE).
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier. Auto-generated from the title if left blank.', max_length=220),
        ),
        migrations.RunPython(backfill_slugs, revert_slugs),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier. Auto-generated from the title if left blank.', max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='number_of_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
