from django.test import TestCase
from django.urls import reverse
from .models import Blog


class BlogModelTests(TestCase):
    def test_str_returns_title(self):
        blog = Blog.objects.create(title="Hello World", content="Body", is_published=True)
        self.assertEqual(str(blog), "Hello World")

    def test_slug_autogenerated(self):
        blog = Blog.objects.create(title="My First Post", content="Body", is_published=True)
        self.assertEqual(blog.slug, "my-first-post")


class BlogViewTests(TestCase):
    def setUp(self):
        self.published = Blog.objects.create(
            title="Published Post", content="Visible", is_published=True
        )
        self.draft = Blog.objects.create(
            title="Draft Post", content="Hidden", is_published=False
        )

    def test_list_shows_only_published(self):
        response = self.client.get(reverse("blog_list"))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, self.published.title)
        self.assertNotContains(response, self.draft.title)

    def test_detail_published_reachable_and_counts_view(self):
        url = reverse("blog_detail", args=[self.published.slug])
        response = self.client.get(url)
        self.assertEqual(response.status_code, 200)
        self.published.refresh_from_db()
        self.assertEqual(self.published.number_of_views, 1)

    def test_detail_draft_returns_404(self):
        url = reverse("blog_detail", args=[self.draft.slug])
        response = self.client.get(url)
        self.assertEqual(response.status_code, 404)
